Arreglé un error en income.spec.js que le tiraba a mis compañeros.
Francisco-G-Montero/gitapp pull request #11
Opened 2021-05-30 23:55 UTC by FlorenciaFried

Solucioné el error "CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is detached from the DOM."

2021-05-30 23:58 UTC, yoelalmiron1997 commented
Revisando

2021-05-31 00:01 UTC, ramiro-c requested changes
Sigue fallando el test

2021-05-31 00:07 UTC, yoelalmiron1997 commented
Si, sigue fallando

2021-05-31 00:10 UTC, Francisco-G-Montero commented
Juntemonos por videollamada y lo vemos entre todos.

2021-05-31 00:12 UTC, yoelalmiron1997 commented
Perfecto, ahí armo el meet y paso el link.

2021-05-31 00:58 UTC, ramiro-c commented
El test solo falla en github, localmente funciona correctamente

2021-05-31 00:59 UTC, ramiro-c commented
El test solo falla en github, localmente se corren correctamente todos los tests

2021-05-31 01:00 UTC, merged